# Generated by Django 6.0 on 2025-12-23 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('CARD', 'Card'), ('TRANSFER', 'Transfer'), ('USSD', 'USSD')], max_length=20)),
                ('reference', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.DateField()),
                ('verified', models.BooleanField(default=True)),
                ('levy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levies.levytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
