# Generated by Django 6.0 on 2025-12-29 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment'),
        ),
    ]
