# Generated by Django 6.0 on 2025-12-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=200),
        ),
        migrations.AlterField(
            model_name='payee',
            name='id_number',
            field=models.CharField(default='123456789', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='occupation',
            field=models.CharField(default='Worker', max_length=100),
        ),
        migrations.AlterField(
            model_name='payee',
            name='phone_number',
            field=models.CharField(default='123456789', max_length=15),
        ),
    ]
