# Generated by Django 6.0 on 2025-12-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_payee_date_of_birth_alter_payee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='id_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='id_type',
            field=models.CharField(choices=[('NIN', 'NIN'), ('TIN', 'TIN'), ('BVN', 'BVN'), ('PHONE', 'Phone Number')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
