# Generated by Django 6.0 on 2025-12-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_payee_email_alter_payee_full_name_and_more'),
        ('levies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='levy_types',
            field=models.ManyToManyField(to='levies.levytype'),
        ),
        migrations.AlterField(
            model_name='payee',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
