# Generated by Django 6.0 on 2025-12-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_payee_levy_types_alter_payee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='passport_photo',
            field=models.ImageField(blank=True, upload_to='passports/'),
        ),
    ]
