# Generated by Django 6.0 on 2025-12-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_payee_passport_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payee',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='payee',
            name='location',
            field=models.CharField(choices=[('Wuse', 'Wuse'), ('Garki', 'Garki'), ('Maitama', 'Maitama'), ('Asokoro', 'Asokoro'), ('Gwarinpa', 'Gwarinpa'), ('Utako', 'Utako'), ('Karu', 'Karu'), ('Nyanya', 'Nyanya')], max_length=20, null=True),
        ),
    ]
